### ISSUE TITLE
Zdjęcia są przypisywane do złych użytkowników

### ISSUE THREAD

**Issue by kpostekk** [pjatk21/pjatk-cat-guard#12]
Ciężko odwzorować ten błąd, nawet nie wiadomo gdzie zacząć.

**Comment by rafalopilowski1** [comment]
https://github.com/pjatk21/pjatk-cat-guard/blob/e410db1f83d4132dab2714d4baace0efa12957ab/webpanel/admin.py#L297

z dokumentacji Mongo w Python
`user = User.objects`**`.get(id=user_id)`**

**Comment by rafalopilowski1** [comment]
Czy jest możliże, że kod bierze wszystkie `VerificationRequest` i przypisuje im dany path do `photoproxy` @kpostekk ?

**Comment by kpostekk** [comment]
Nigdzie w dokumentacji `mongoengine` nie znalazłem, żeby robili to tak jak ja. Zapewne to może być przyczyna.

**Comment by kpostekk** [comment]
> Czy jest możliże, że kod bierze wszystkie `VerificationRequest` i przypisuje im dany path do `photoproxy` @kpostekk ?

Mam wątpliwości bo bug jest również widoczny w `admin:admin_index` gdzie oznacza wszystkich jako oczekujących na sprawdzenia zdjęcia.

**Comment by kpostekk** [comment]
Błąd musi myć stricte runtime'owy, ponieważ zwykły restart go naprawia i ciężko określić kiedy taki błąd powstaje.

**Comment by rafalopilowski1** [comment]
Po obserwacji, chyba poprawa syntaxu pomogła - zamykam, aż znowu się nie pojawi @kpostekk

**Comment by kpostekk** [comment]
Błąd wciąż istnieje

**Comment by rafalopilowski1** [comment]
https://github.com/pjatk21/pjatk-cat-guard/blob/e12a20cb7e7edbbb9e1373aa7efebbd739b60695/shared/documents.py#L106-L108

Może zróbmy tak:

```python
@property
def ready(self):
    return not (not self.front.to_python() or not self.back.to_python())
```

**Comment by kpostekk** [comment]
Czemu?

**Comment by rafalopilowski1** [comment]
> Czemu?

`self.from` i `self.back` to jest `StringField` Mongo, a nie natywny `str` Pythona - może w tym jest problem...

**Comment by kpostekk** [comment]
> > Czemu?
> 
> `self.from` i `self.back` to jest `StringField` Mongo, a nie natywny `str` Pythona - może w tym jest problem...

`from` i `back` są `None` jeżeli nie są ustawione

**Comment by kpostekk** [comment]
Błąd przestał się pojawiać. Zamykam
