### ISSUE TITLE
User not being removed from database while autokick

### ISSUE THREAD

**Issue by rafalopilowski1** [pjatk21/pjatk-cat-guard#30]
Example:
![obraz](https://user-images.githubusercontent.com/11944411/159005288-65ed8829-122a-49f7-a19c-3d2e47d87032.png)
(via bypass, kicked by TAK ban)

**Comment by kpostekk** [comment]
Interesting, looks like it bot doesn't listen for own events. This will be fixed soon.

**Comment by kpostekk** [comment]
fixed in 4c6021d1e2522b01eac794ce46e410818184007d
