### ISSUE TITLE
Redesign subpages

### ISSUE THREAD

**Issue by kpostekk** [pjatk21/pjatk-cat-guard#6]
I think using 98.css for subpages like confirmations and invites would be fun.

**Comment by rafalopilowski1** [comment]
@kpostekk

| Desktop | Mobile (iPhone 11 Pro) |
|---|---|
|![Homepage_Desktop](https://user-images.githubusercontent.com/11944411/150635495-24513351-6d8b-4395-b0fe-aef00c9457f6.png)|![Homepage_Mobile](https://user-images.githubusercontent.com/11944411/150635564-373c5a76-fbef-4445-8611-457ea06758e9.png)|
|![Guild_Invite_Desktop](https://user-images.githubusercontent.com/11944411/150635504-f4cd943c-4e40-4313-9ab9-3925a32e9f72.png)|![Guild_Invite_Mobile](https://user-images.githubusercontent.com/11944411/150635570-80d0b75e-4ad0-4f0c-8654-5d452f36dd71.png)|
|![Guild_Invited_Desktop](https://user-images.githubusercontent.com/11944411/150635507-1eeed6d8-1b77-4128-ade1-0c1cab0eaa5e.png)|![Guild_Invited_Mobile](https://user-images.githubusercontent.com/11944411/150635582-d7b799dc-83c9-4198-b2a4-973ba9aa2578.png)|

**Comment by kpostekk** [comment]
I would leave commodore style at home page, and use 98 style with other pages

**Comment by rafalopilowski1** [comment]
> I would leave commodore style at home page, and use 98 style with other pages

I don't think it will look good and consistent

**Comment by kpostekk** [comment]
Ok
