### ISSUE TITLE
Sugestia delikatnego udoskonalenie logowania przez google

### ISSUE THREAD

**Issue by ImJustToNy** [pjatk21/pjatk-cat-guard#9]
Jeżeli wysyłamy usera do google connect (oauth redirect), możemy wysłać dodatkowy
parametr *&hd=pjwstk.edu.pl*, który zasugeruje przeglądarce że powinna pokazywać tylko konta z domeny pjwstk.edu.pl.

https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param

**Comment by kpostekk** [comment]
> Jeżeli wysyłamy usera do google connect (oauth redirect)

W tym problem, że używam Google Identity Service, który nie jest OAuthem. Jest stricte to pobierania minimalnych danych o użytkowniku. Dokumentacja dla GIS nic nie wspomina o takim parametrze.
